import Header from '@/components/Header';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body>
        <Header />
        <div className="flex flex-col min-h-screen">
            <main className="flex-1 bg-gray-100">
                {children}
            </main>
        </div>
        </body>
        </html>
    );
}
